# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
- id: terraform-provider-grafana
  env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
  binary: '{{ .ProjectName }}_v{{ .Version }}'
- id: terraform-provider-grafana-generate
  env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}}'
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
  main: ./cmd/generate
  binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
- id: terraform-provider-grafana
  format: zip
  name_template: 'terraform-provider-grafana_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  builds:
    - terraform-provider-grafana
- id: terraform-provider-grafana-generate
  format: binary
  name_template: 'terraform-provider-grafana-generate_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  builds:
    - terraform-provider-grafana-generate
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this is a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  # If you want to manually examine the release before it's live, uncomment this line:
  draft: true
changelog:
  disable: true
