---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-provider-grafana
  title: terraform-provider-grafana
  description: |
    Grafana Labs' Terraform Provider
  links:
    - title: Slack Channel
      url: https://raintank-corp.slack.com/archives/C02S85R5064
  annotations:
    github.com/project-slug: grafana/terraform-provider-grafana
spec:
  type: tool
  owner: group:default/platform-monitoring
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: terraform-resources
spec:
  type: url
  targets:
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/appplatform/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/cloud/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/cloudprovider/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/connections/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/fleetmanagement/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/frontendo11y/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/grafana/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/k6/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/machinelearning/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/oncall/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/slo/catalog-resource.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/syntheticmonitoring/catalog-resource.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: terraform-data-sources
spec:
  type: url
  targets:
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/cloud/catalog-data-source.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/cloudprovider/catalog-data-source.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/connections/catalog-data-source.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/fleetmanagement/catalog-data-source.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/frontendo11y/catalog-data-source.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/grafana/catalog-data-source.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/k6/catalog-data-source.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/oncall/catalog-data-source.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/slo/catalog-data-source.yaml
    - https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/syntheticmonitoring/catalog-data-source.yaml
