apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-provider-grafana
  title: terraform-provider-grafana
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: grafana/terraform-provider-grafana
spec:
  type: tool
  owner: group:backstage-catalog/platform-monitoring
  lifecycle: production
