[changelog]
header = ""
body = """
{% macro pr_link(commit) %}{% if commit.remote.pr_number %} ([#{{ commit.remote.pr_number }}](https://github.com/grafana/terraform-provider-grafana/pull/{{ commit.remote.pr_number }})){% endif %}{% endmacro %}
{% macro commit_line(commit) %}- {% if commit.scope and commit.scope != "_unscoped" %}**{{ commit.scope }}:** {% endif %}{{ commit.message }}{{ self::pr_link(commit=commit) }}{% if commit.remote.username %} by @{{ commit.remote.username }}{% endif %}{% endmacro %}

{% for group, group_commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in group_commits -%}
{{ self::commit_line(commit=commit) }}
{% endfor -%}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
commit_preprocessors = [
    { pattern = ' *\(#\d+\)', replace = "" },
    { pattern = '\n.*', replace = "" },
]
filter_unconventional = false
protect_breaking_commits = true
commit_parsers = [
    { message = "^feat", group = "Features", default_scope = "_unscoped" },
    { message = "^fix", group = "Bug Fixes", default_scope = "_unscoped" },
    { message = "^docs", group = "Documentation", default_scope = "_unscoped" },
    { message = "^perf", group = "Performance", default_scope = "_unscoped" },
    { message = "^refactor", group = "Refactoring", default_scope = "_unscoped" },
    { message = "^style", group = "Styling", default_scope = "_unscoped" },
    { message = "^test", group = "Testing", default_scope = "_unscoped" },
    { message = "^chore", group = "Miscellaneous", default_scope = "_unscoped" },
    { message = "^ci", group = "CI/CD", default_scope = "_unscoped" },
    { message = "^build", group = "Build", default_scope = "_unscoped" },
    { message = ".*", group = "Other Changes", default_scope = "_unscoped" },
]
tag_pattern = "v[0-9].*"
sort_commits = "oldest"

[remote.github]
owner = "grafana"
repo = "terraform-provider-grafana"
