---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_asserts_notification_alerts_config
  title: grafana_asserts_notification_alerts_config (resource)
  description: |
    resource `grafana_asserts_notification_alerts_config` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/asserts
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_asserts_suppressed_assertions_config
  title: grafana_asserts_suppressed_assertions_config (resource)
  description: |
    resource `grafana_asserts_suppressed_assertions_config` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/asserts
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_asserts_custom_model_rules
  title: grafana_asserts_custom_model_rules (resource)
  description: |
    resource `grafana_asserts_custom_model_rules` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/asserts
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_asserts_log_config
  title: grafana_asserts_log_config (resource)
  description: |
    resource `grafana_asserts_log_config` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/asserts
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_asserts_trace_config
  title: grafana_asserts_trace_config (resource)
  description: |
    resource `grafana_asserts_trace_config` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/asserts
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_asserts_profile_config
  title: grafana_asserts_profile_config (resource)
  description: |
    resource `grafana_asserts_profile_config` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/asserts
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_asserts_prom_rule_file
  title: grafana_asserts_prom_rule_file (resource)
  description: |
    resource `grafana_asserts_prom_rule_file` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/asserts
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: resource-grafana_asserts_thresholds
  title: grafana_asserts_thresholds (resource)
  description: |
    resource `grafana_asserts_thresholds` in Grafana Labs' Terraform Provider
spec:
  subcomponentOf: component:default/terraform-provider-grafana
  type: terraform-resource
  owner: group:default/asserts
  lifecycle: production
