package asserts

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	assertsapi "github.com/grafana/grafana-asserts-public-clients/go/gcom"
	"github.com/grafana/terraform-provider-grafana/v4/internal/common"
)

func makeResourceAlertConfig() *common.Resource {
	schema := &schema.Resource{
		Description: "Manages Asserts Alert Configurations through Grafana API.",

		CreateContext: resourceAlertConfigCreate,
		ReadContext:   resourceAlertConfigRead,
		UpdateContext: resourceAlertConfigUpdate,
		DeleteContext: resourceAlertConfigDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},

		Schema: map[string]*schema.Schema{
			"name": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true, // Force recreation if name changes
				Description: "The name of the alert configuration.",
			},
			"match_labels": {
				Type:        schema.TypeMap,
				Optional:    true,
				Description: "Labels to match for this alert configuration.",
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"alert_labels": {
				Type:        schema.TypeMap,
				Optional:    true,
				Description: "Labels to add to alerts generated by this configuration.",
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"duration": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Duration for which the condition must be true before firing (e.g., '5m', '30s'). Maps to 'for' in Asserts API.",
			},
			"silenced": {
				Type:     schema.TypeBool,
				Optional: true,
				Default:  false,

				Description: "Whether this alert configuration is silenced.",
			},
		},
	}

	return common.NewLegacySDKResource(
		common.CategoryAsserts,
		"grafana_asserts_notification_alerts_config",
		common.NewResourceID(common.StringIDField("name")),
		schema,
	).WithLister(assertsListerFunction(listAlertConfigs))
}

func resourceAlertConfigCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client, stackID, diags := validateAssertsClient(meta)
	if diags.HasError() {
		return diags
	}
	name := d.Get("name").(string)
	matchLabels := make(map[string]string)
	alertLabels := make(map[string]string)

	if v, ok := d.GetOk("match_labels"); ok {
		for k, val := range v.(map[string]interface{}) {
			matchLabels[k] = val.(string)
		}
	}

	if v, ok := d.GetOk("alert_labels"); ok {
		for k, val := range v.(map[string]interface{}) {
			alertLabels[k] = val.(string)
		}
	}

	duration := d.Get("duration").(string)
	silenced := d.Get("silenced").(bool)

	// Create AlertConfigDto using the generated client models
	// Only include non-empty maps to avoid validation issues
	alertConfig := assertsapi.AlertConfigDto{
		Name:     &name,
		Silenced: &silenced,
	}

	// Only set matchLabels if not empty
	if len(matchLabels) > 0 {
		alertConfig.MatchLabels = matchLabels
	}

	// Only set alertLabels if not empty
	if len(alertLabels) > 0 {
		alertConfig.AlertLabels = alertLabels
	}

	// Only set duration if not empty
	if duration != "" {
		alertConfig.For = &duration
	}

	// Call the generated client API
	request := client.AlertConfigurationAPI.PutAlertConfig(ctx).
		AlertConfigDto(alertConfig).
		XScopeOrgID(fmt.Sprintf("%d", stackID))

	_, err := request.Execute()
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create alert configuration: %w", err))
	}

	d.SetId(name)

	return resourceAlertConfigRead(ctx, d, meta)
}

func resourceAlertConfigRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client, stackID, diags := validateAssertsClient(meta)
	if diags.HasError() {
		return diags
	}
	name := d.Id()

	// Retry logic for read operation to handle eventual consistency
	var foundConfig *assertsapi.AlertConfigDto
	err := withRetryRead(ctx, func(retryCount, maxRetries int) *retry.RetryError {
		// Get all alert configs using the generated client API
		request := client.AlertConfigurationAPI.GetAllAlertConfigs(ctx).
			XScopeOrgID(fmt.Sprintf("%d", stackID))

		alertConfigs, _, err := request.Execute()
		if err != nil {
			return createAPIError("get alert configurations", retryCount, maxRetries, err)
		}

		// Find our specific config
		for _, config := range alertConfigs.AlertConfigs {
			if config.Name != nil && *config.Name == name {
				foundConfig = &config
				return nil
			}
		}

		// Check if we should give up or retry
		if retryCount >= maxRetries {
			return createNonRetryableError("alert configuration", name, retryCount)
		}
		return createRetryableError("alert configuration", name, retryCount, maxRetries)
	})

	if err != nil {
		return diag.FromErr(err)
	}

	if foundConfig == nil {
		d.SetId("")
		return nil
	}

	// Set the resource data
	if foundConfig.Name != nil {
		if err := d.Set("name", *foundConfig.Name); err != nil {
			return diag.FromErr(err)
		}
	}
	if foundConfig.MatchLabels != nil {
		if err := d.Set("match_labels", foundConfig.MatchLabels); err != nil {
			return diag.FromErr(err)
		}
	}
	if foundConfig.AlertLabels != nil {
		if err := d.Set("alert_labels", foundConfig.AlertLabels); err != nil {
			return diag.FromErr(err)
		}
	}
	if foundConfig.For != nil {
		if err := d.Set("duration", *foundConfig.For); err != nil {
			return diag.FromErr(err)
		}
	}
	if foundConfig.Silenced != nil {
		if err := d.Set("silenced", *foundConfig.Silenced); err != nil {
			return diag.FromErr(err)
		}
	}

	return nil
}

func resourceAlertConfigUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client, stackID, diags := validateAssertsClient(meta)
	if diags.HasError() {
		return diags
	}

	name := d.Get("name").(string)
	matchLabels := make(map[string]string)
	alertLabels := make(map[string]string)

	if v, ok := d.GetOk("match_labels"); ok {
		for k, val := range v.(map[string]interface{}) {
			matchLabels[k] = val.(string)
		}
	}

	if v, ok := d.GetOk("alert_labels"); ok {
		for k, val := range v.(map[string]interface{}) {
			alertLabels[k] = val.(string)
		}
	}

	duration := d.Get("duration").(string)
	silenced := d.Get("silenced").(bool)

	// Create AlertConfigDto using the generated client models
	// Only include non-empty maps to avoid validation issues
	alertConfig := assertsapi.AlertConfigDto{
		Name:     &name,
		Silenced: &silenced,
	}

	// Only set matchLabels if not empty
	if len(matchLabels) > 0 {
		alertConfig.MatchLabels = matchLabels
	}

	// Only set alertLabels if not empty
	if len(alertLabels) > 0 {
		alertConfig.AlertLabels = alertLabels
	}

	// Only set duration if not empty
	if duration != "" {
		alertConfig.For = &duration
	}

	// Update Alert Configuration using the generated client API
	request := client.AlertConfigurationAPI.PutAlertConfig(ctx).
		AlertConfigDto(alertConfig).
		XScopeOrgID(fmt.Sprintf("%d", stackID))

	_, err := request.Execute()
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update alert configuration: %w", err))
	}

	return resourceAlertConfigRead(ctx, d, meta)
}

func resourceAlertConfigDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client, stackID, diags := validateAssertsClient(meta)
	if diags.HasError() {
		return diags
	}
	name := d.Id()

	// Delete Alert Configuration using the generated client API
	request := client.AlertConfigurationAPI.DeleteAlertConfig(ctx, name).
		XScopeOrgID(fmt.Sprintf("%d", stackID))

	_, err := request.Execute()
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to delete alert configuration: %w", err))
	}

	return nil
}
