# Test that we don't get a diff when uid is unset.
# In this case, it will be generated by Grafana.
resource "grafana_library_panel" "test" {
  name          = "uid-unset"
  folder_id     = 0
  model_json    = jsonencode({
    title       = "UID Unset",
    description = "uid-unset",
    type        = "dash-db",
  })
}
