package slo

import (
	"context"
	"encoding/json"
	"regexp"

	"github.com/grafana/slo-openapi-client/go/slo"
	"github.com/grafana/terraform-provider-grafana/v4/internal/common"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

// datasourceSloResourceSchema returns an SDKv2 schema.Resource that mirrors the
// grafana_slo resource schema. It is used by the datasource to clone for the
// "slos" list element. This was previously obtained via resourceSlo().Schema
// but is now defined separately since the resource moved to Plugin Framework.
func datasourceSloResourceSchema() *schema.Resource {
	keyvalueSchema := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"key": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Key for filtering and identification`,
			},
			"value": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Templatable value`,
			},
		},
	}

	enrichmentSchema := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"type": {
				Type:         schema.TypeString,
				Required:     true,
				Description:  `Type of the alert enrichment. Currently only "assistantInvestigation" is supported.`,
				ValidateFunc: validation.StringInSlice([]string{"assistantInvestigation"}, false),
			},
		},
	}

	return &schema.Resource{
		Schema: map[string]*schema.Schema{
			"name": {
				Type:         schema.TypeString,
				Required:     true,
				Description:  `Name should be a short description of your indicator. Consider names like "API Availability"`,
				ValidateFunc: validation.StringLenBetween(0, 128),
			},
			"description": {
				Type:         schema.TypeString,
				Required:     true,
				Description:  `Description is a free-text field that can provide more context to an SLO.`,
				ValidateFunc: validation.StringLenBetween(0, 1024),
			},
			"folder_uid": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `UID for the SLO folder`,
			},
			"uuid": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `UUID for the SLO. Custom UUIDs can be set. If not provided, a random UUID will be generated by the API.`,
			},
			"destination_datasource": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Required:    true,
				Description: `Destination Datasource sets the datasource defined for an SLO`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"uid": {
							Type:        schema.TypeString,
							Description: `UID for the Datasource`,
							Required:    true,
						},
					},
				},
			},
			"query": {
				Type:        schema.TypeList,
				Required:    true,
				Description: `Query describes the indicator that will be measured against the objective. Freeform Query types are currently supported.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"type": {
							Type:         schema.TypeString,
							Description:  `Query type must be one of: "freeform", "query", "ratio", "grafana_queries" or "threshold"`,
							ValidateFunc: validation.StringInSlice([]string{"freeform", "query", "ratio", "threshold", "grafana_queries"}, false),
							Required:     true,
						},
						"freeform": {
							Type:     schema.TypeList,
							MaxItems: 1,
							Optional: true,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"query": {
										Type:        schema.TypeString,
										Required:    true,
										Description: "Freeform Query Field - valid promQl",
									},
								},
							},
						},
						"grafana_queries": {
							Type:        schema.TypeList,
							MaxItems:    1,
							Optional:    true,
							Description: "Array for holding a set of grafana queries",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"grafana_queries": {
										Type:             schema.TypeString,
										Required:         true,
										Description:      "Query Object - Array of Grafana Query JSON objects",
										ValidateDiagFunc: ValidateGrafanaQuery(),
									},
								},
							},
						},
						"ratio": {
							Type:     schema.TypeList,
							MaxItems: 1,
							Optional: true,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"success_metric": {
										Type:        schema.TypeString,
										Description: `Counter metric for success events (numerator)`,
										Required:    true,
									},
									"total_metric": {
										Type:        schema.TypeString,
										Description: `Metric for total events (denominator)`,
										Required:    true,
									},
									"group_by_labels": {
										Type:        schema.TypeList,
										Description: `Defines Group By Labels used for per-label alerting. These appear as variables on SLO dashboards to enable filtering and aggregation. Labels must adhere to Prometheus label name schema - "^[a-zA-Z_][a-zA-Z0-9_]*$"`,
										Optional:    true,
										Elem: &schema.Schema{
											Type: schema.TypeString,
										},
									},
								},
							},
						},
					},
				},
			},
			"label": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: `Additional labels that will be attached to all metrics generated from the query. These labels are useful for grouping SLOs in dashboard views that you create by hand. Labels must adhere to Prometheus label name schema - "^[a-zA-Z_][a-zA-Z0-9_]*$"`,
				Elem:        keyvalueSchema,
			},
			"objectives": {
				Type:        schema.TypeList,
				Required:    true,
				Description: `Over each rolling time window, the remaining error budget will be calculated, and separate alerts can be generated for each time window based on the SLO burn rate or remaining error budget.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"value": {
							Type:         schema.TypeFloat,
							Required:     true,
							ValidateFunc: validation.FloatBetween(0, 1),
							Description:  `Value between 0 and 1. If the value of the query is above the objective, the SLO is met.`,
						},
						"window": {
							Type:         schema.TypeString,
							Required:     true,
							Description:  `A Prometheus-parsable time duration string like 24h, 60m. This is the time window the objective is measured over.`,
							ValidateFunc: validation.StringMatch(regexp.MustCompile(`^\d+(ms|s|m|h|d|w|y)$`), "Objective window must be a Prometheus-parsable time duration"),
						},
					},
				},
			},
			"alerting": {
				Type:     schema.TypeList,
				MaxItems: 1,
				Optional: true,
				Description: `Configures the alerting rules that will be generated for each
				time window associated with the SLO. Grafana SLOs can generate
				alerts when the short-term error budget burn is very high, the
				long-term error budget burn rate is high, or when the remaining
				error budget is below a certain threshold. Annotations and Labels support templating.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"label": {
							Type:        schema.TypeList,
							Optional:    true,
							Description: `Labels will be attached to all alerts generated by any of these rules.`,
							Elem:        keyvalueSchema,
						},
						"annotation": {
							Type:        schema.TypeList,
							Optional:    true,
							Description: `Annotations will be attached to all alerts generated by any of these rules.`,
							Elem:        keyvalueSchema,
						},
						"fastburn": {
							Type:        schema.TypeList,
							Optional:    true,
							MaxItems:    1,
							Description: "Alerting Rules generated for Fast Burn alerts",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"label": {
										Type:        schema.TypeList,
										Optional:    true,
										Description: "Labels to attach only to Fast Burn alerts.",
										Elem:        keyvalueSchema,
									},
									"annotation": {
										Type:        schema.TypeList,
										Optional:    true,
										Description: "Annotations to attach only to Fast Burn alerts.",
										Elem:        keyvalueSchema,
									},
									"enrichment": {
										Type:        schema.TypeList,
										Optional:    true,
										Description: "Enrichments to attach only to Fast Burn alerts.",
										Elem:        enrichmentSchema,
									},
								},
							},
						},
						"slowburn": {
							Type:        schema.TypeList,
							MaxItems:    1,
							Optional:    true,
							Description: "Alerting Rules generated for Slow Burn alerts",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"label": {
										Type:        schema.TypeList,
										Optional:    true,
										Description: "Labels to attach only to Slow Burn alerts.",
										Elem:        keyvalueSchema,
									},
									"annotation": {
										Type:        schema.TypeList,
										Optional:    true,
										Description: "Annotations to attach only to Slow Burn alerts.",
										Elem:        keyvalueSchema,
									},
									"enrichment": {
										Type:        schema.TypeList,
										Optional:    true,
										Description: "Enrichments to attach only to Slow Burn alerts.",
										Elem:        enrichmentSchema,
									},
								},
							},
						},
						"advanced_options": {
							Type:        schema.TypeList,
							MaxItems:    1,
							Optional:    true,
							Description: "Advanced Options for Alert Rules",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"min_failures": {
										Type:         schema.TypeInt,
										Optional:     true,
										Description:  "Minimum number of failed events to trigger an alert",
										ValidateFunc: validation.IntAtLeast(0),
									},
								},
							},
						},
					},
				},
			},
			"search_expression": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The name of a search expression in Grafana Asserts. This is used in the SLO UI to open the Asserts RCA workbench and in alerts to link to the RCA workbench.",
			},
		},
	}
}

func datasourceSlo() *common.DataSource {
	schema := &schema.Resource{
		Description: `
Datasource for retrieving all SLOs.
		
* [Official documentation](https://grafana.com/docs/grafana-cloud/alerting-and-irm/slo/)
* [API documentation](https://grafana.com/docs/grafana-cloud/alerting-and-irm/slo/api/)
* [Additional Information On Alerting Rule Annotations and Labels](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating/)
				`,
		ReadContext: withClient[schema.ReadContextFunc](datasourceSloRead),
		Schema: map[string]*schema.Schema{
			"slos": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `Returns a list of all SLOs"`,
				Elem: &schema.Resource{
					Schema: common.CloneResourceSchemaForDatasource(datasourceSloResourceSchema(), map[string]*schema.Schema{
						"uuid": {
							Type:        schema.TypeString,
							Description: `A unique, random identifier. This value will also be the name of the resource stored in the API server. This value is read-only.`,
							Computed:    true,
						},
					}),
				},
			},
		},
	}
	return common.NewLegacySDKDataSource(common.CategorySLO, "grafana_slos", schema)
}

// Function sends a GET request to the SLO API Endpoint which returns a list of all SLOs
// Maps the API Response body to the Terraform Schema and displays as a READ in the terminal
func datasourceSloRead(ctx context.Context, d *schema.ResourceData, client *slo.APIClient) diag.Diagnostics {
	var diags diag.Diagnostics

	req := client.DefaultAPI.V1SloGet(ctx)
	apiSlos, _, err := req.Execute()
	if err != nil {
		return diag.Diagnostics{diag.Diagnostic{
			Severity: diag.Error,
			Summary:  "Could not retrieve SLOs",
			Detail:   formatAPIError(err),
		}}
	}

	terraformSlos := []any{}

	if len(apiSlos.Slos) == 0 {
		d.SetId("slos")
		d.Set("slos", terraformSlos)
		return diags
	}

	for _, slo := range apiSlos.Slos {
		terraformSlo := convertDatasourceSlo(slo)
		terraformSlos = append(terraformSlos, terraformSlo)
	}

	d.SetId("slos")
	d.Set("slos", terraformSlos)

	return diags
}

func convertDatasourceSlo(slo slo.SloV00Slo) map[string]any {
	ret := make(map[string]any)

	ret["uuid"] = slo.Uuid
	ret["name"] = slo.Name
	ret["description"] = slo.Description

	ret["query"] = unpackQuery(slo.Query)

	ret["destination_datasource"] = unpackDestinationDatasource(slo.DestinationDatasource)

	retLabels := unpackLabels(slo.Labels)
	ret["label"] = retLabels

	retObjectives := unpackObjectives(slo.Objectives)
	ret["objectives"] = retObjectives

	retAlerting := unpackAlerting(slo.Alerting)
	ret["alerting"] = retAlerting
	ret["search_expression"] = slo.SearchExpression

	return ret
}

func unpackQuery(apiquery slo.SloV00Query) []map[string]any {
	retQuery := []map[string]any{}

	if apiquery.Type == QueryTypeFreeform {
		query := map[string]any{"type": QueryTypeFreeform}

		freeformquerystring := map[string]any{"query": apiquery.Freeform.Query}
		freeform := []map[string]any{}
		freeform = append(freeform, freeformquerystring)
		query["freeform"] = freeform

		retQuery = append(retQuery, query)
	}

	if apiquery.Type == QueryTypeRatio {
		query := map[string]any{"type": QueryTypeRatio}

		ratio := []map[string]any{}
		body := map[string]any{
			"success_metric":  apiquery.Ratio.SuccessMetric.PrometheusMetric,
			"total_metric":    apiquery.Ratio.TotalMetric.PrometheusMetric,
			"group_by_labels": apiquery.Ratio.GroupByLabels,
		}

		ratio = append(ratio, body)
		query["ratio"] = ratio

		retQuery = append(retQuery, query)
	}

	if apiquery.Type == QueryTypeGrafanaQueries {
		query := map[string]any{"type": "grafana_queries"}

		grafanaQueries := []map[string]any{}
		queryString, _ := json.Marshal(apiquery.GrafanaQueries.GetGrafanaQueries())
		grafanaQueriesString := map[string]any{"grafana_queries": string(queryString)}
		grafanaQueries = append(grafanaQueries, grafanaQueriesString)
		query["grafana_queries"] = grafanaQueries
		retQuery = append(retQuery, query)
	}

	return retQuery
}

func unpackObjectives(objectives []slo.SloV00Objective) []map[string]any {
	retObjectives := []map[string]any{}

	for _, objective := range objectives {
		retObjective := make(map[string]any)
		retObjective["value"] = objective.Value
		retObjective["window"] = objective.Window
		retObjectives = append(retObjectives, retObjective)
	}

	return retObjectives
}

func unpackLabels(labelsInterface any) []map[string]any {
	retLabels := []map[string]any{}

	var labels []slo.SloV00Label
	switch v := labelsInterface.(type) {
	case *[]slo.SloV00Label:
		labels = *v
	case []slo.SloV00Label:
		labels = v
	case []any:
		for _, labelInterface := range v {
			switch v := labelInterface.(type) {
			case map[string]any:
				label := slo.SloV00Label{
					Key:   v["key"].(string),
					Value: v["value"].(string),
				}
				labels = append(labels, label)
			case slo.SloV00Label:
				labels = append(labels, v)
			}
		}
	}

	for _, label := range labels {
		retLabel := make(map[string]any)
		retLabel["key"] = label.Key
		retLabel["value"] = label.Value
		retLabels = append(retLabels, retLabel)
	}
	return retLabels
}

func unpackAlerting(alertData *slo.SloV00Alerting) []map[string]any {
	retAlertData := []map[string]any{}

	if alertData == nil {
		return retAlertData
	}

	alertObject := make(map[string]any)
	alertObject["label"] = unpackLabels(alertData.Labels)
	alertObject["annotation"] = unpackLabels(alertData.Annotations)

	if alertData.FastBurn != nil {
		alertObject["fastburn"] = unpackAlertingMetadata(*alertData.FastBurn)
	}

	if alertData.SlowBurn != nil {
		alertObject["slowburn"] = unpackAlertingMetadata(*alertData.SlowBurn)
	}

	if alertData.AdvancedOptions != nil {
		alertObject["advanced_options"] = unpackAdvancedOptions(*alertData.AdvancedOptions)
	}

	retAlertData = append(retAlertData, alertObject)
	return retAlertData
}

func unpackAlertingMetadata(metaData slo.SloV00AlertingMetadata) []map[string]any {
	retAlertMetaData := []map[string]any{}
	labelsAnnotsStruct := make(map[string]any)

	if metaData.Annotations != nil {
		retAnnotations := unpackLabels(metaData.Annotations)
		labelsAnnotsStruct["annotation"] = retAnnotations
	}

	if metaData.Labels != nil {
		retLabels := unpackLabels(metaData.Labels)
		labelsAnnotsStruct["label"] = retLabels
	}

	if metaData.Enrichments != nil {
		retEnrichments := unpackEnrichments(metaData.Enrichments)
		labelsAnnotsStruct["enrichment"] = retEnrichments
	}

	retAlertMetaData = append(retAlertMetaData, labelsAnnotsStruct)
	return retAlertMetaData
}

func unpackEnrichments(enrichments []slo.SloV00AlertEnrichment) []map[string]any {
	retEnrichments := []map[string]any{}
	for _, enrichment := range enrichments {
		retEnrichment := make(map[string]any)
		retEnrichment["type"] = enrichment.Type
		retEnrichments = append(retEnrichments, retEnrichment)
	}
	return retEnrichments
}

func unpackAdvancedOptions(options slo.SloV00AdvancedOptions) []map[string]any {
	retAdvancedOptions := []map[string]any{}
	minFailuresStruct := make(map[string]any)

	if options.MinFailures != nil {
		minFailuresStruct["min_failures"] = int(*options.MinFailures)
	}

	retAdvancedOptions = append(retAdvancedOptions, minFailuresStruct)
	return retAdvancedOptions
}

func unpackDestinationDatasource(destinationDatasource *slo.SloV00DestinationDatasource) []map[string]any {
	retDestinationDatasources := []map[string]any{}

	retDestinationDatasource := make(map[string]any)
	retDestinationDatasource["uid"] = destinationDatasource.Uid

	retDestinationDatasources = append(retDestinationDatasources, retDestinationDatasource)

	return retDestinationDatasources
}
