name: Feature Request
description: Suggest an idea for this provider
title: "[Feature Request]: "
labels: ["enhancement"]
projects: ["grafana/513"] # Platform Client Administration Tooling
body:
  - type: textarea
    id: request
    attributes:
      label: Feature Request
      placeholder: |
        What would you like to see added to the Grafana provider?
