name: Feature Request
description: Suggest an idea for this provider
title: ""
type: "enhancement"
projects: ["grafana/513"] # Platform Monitoring
body:
  - type: textarea
    id: request
    attributes:
      label: Feature Request
      placeholder: |
        What would you like to see added to the Grafana provider?
