blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/grafana/terraform-provider-grafana/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
