name: Validate catalog
description: Validate Backstage catalog information

runs:
  using: composite
  steps:
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version-file: go.mod

    - name: Setup jsonnet
      id: setup-jsonnet
      uses: zendesk/setup-jsonnet@f683a0d16f479db69751bd8d3a49a09e22b45b39 # v12

    - name: Setup terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

    - name: Generate provider schema
      id: generate-schema
      shell: bash
      run: ./scripts/generate_schema.sh > schema.json

    - name: Validate catalog
      id: validate-catalog
      shell: bash
      run: |
        jsonnet -S \
            --tla-str-file "catalog=./catalog-info.yaml" \
            "./.github/actions/validate-catalog/locations.jsonnet" | xargs cat > catalog.yaml

        jsonnet -S \
            --tla-str-file catalog=catalog.yaml \
            --tla-code-file schema=schema.json \
            "./.github/actions/validate-catalog/validate.jsonnet"
