package main

import (
	"context"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/charmbracelet/huh"
	"github.com/grafana/terraform-provider-grafana/scripts/add-resource/codegen"
)

func main() {
	cwd, err := os.Getwd()
	abortIfErr(err)

	rootOutputDir := filepath.Join(cwd, "..", "..")

	// Step 1: Collect the manifest URL.
	var goTypesImportPath string
	var manifestURL string
	abortIfErr(huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("Manifest URL").
				Description("Raw GitHub URL for a Grafana manifest.cue file.\nExample: https://raw.githubusercontent.com/grafana/grafana/refs/heads/main/apps/advisor/kinds/manifest.cue").
				Validate(func(s string) error {
					u, err := url.ParseRequestURI(s)
					if err != nil {
						return err
					}
					if !strings.HasSuffix(path.Base(u.Path), ".cue") {
						return fmt.Errorf("must be a .cue file")
					}
					return nil
				}).
				Value(&manifestURL),
			huh.NewInput().
				Title("Go types import path").
				Description("Import path for the Go types generated by the App SDK.\nExample: github.com/grafana/grafana/apps/advisor/pkg/apis/advisor/v0alpha1").
				Value(&goTypesImportPath),
		),
	).Run())

	// Step 2: Fetch and parse the manifest.
	fmt.Println("Fetching manifest…")
	manifest, err := codegen.FetchAndParseManifest(manifestURL)
	if err != nil {
		panic(fmt.Errorf("failed to parse manifest: %w", err))
	}

	fmt.Println()
	codegen.PrintManifestSummary(manifest)
	fmt.Println()

	// Step 3: Select version.
	versions := codegen.ManifestVersions(manifest)
	if len(versions) == 0 {
		panic("no versions found in manifest")
	}

	var selectedVersion string
	if len(versions) == 1 {
		selectedVersion = versions[0]
		fmt.Printf("Selected version: %s (only one available)\n", selectedVersion)
	} else {
		opts := make([]huh.Option[string], len(versions))
		for i, v := range versions {
			opts[i] = huh.NewOption(v, v)
		}
		abortIfErr(huh.NewForm(
			huh.NewGroup(
				huh.NewSelect[string]().
					Title("Select version").
					Description("Available versions from the manifest.").
					Options(opts...).
					Value(&selectedVersion),
			),
		).Run())
	}

	// Step 4: Select kind.
	kinds := codegen.KindsForVersion(manifest, selectedVersion)
	if len(kinds) == 0 {
		panic(fmt.Sprintf("no kinds found for version %s", selectedVersion))
	}
	var selectedKindName string
	if len(kinds) == 1 {
		selectedKindName = kinds[0].Kind
		fmt.Printf("Kind: %s (only one available)\n", selectedKindName)
	} else {
		opts := make([]huh.Option[string], len(kinds))
		for i, k := range kinds {
			opts[i] = huh.NewOption(k.Kind, k.Kind)
		}
		abortIfErr(huh.NewForm(
			huh.NewGroup(
				huh.NewSelect[string]().
					Title("Select kind").
					Description(fmt.Sprintf("Available kinds for version %s.", selectedVersion)).
					Options(opts...).
					Value(&selectedKindName),
			),
		).Run())
	}

	// Step 5: Find the kind file and extract kind metadata.
	fmt.Printf("Looking up kind %q…\n", selectedKindName)
	kindInfo, err := codegen.FindKind(manifest, selectedKindName, selectedVersion)
	if err != nil {
		panic(err)
	}

	fmt.Println()
	codegen.PrintKindSummary(kindInfo)
	fmt.Println()

	// Step 6: Ask for schema name, output directory, and formatting option.
	var resourceDir string
	var skipFormatting bool

	abortIfErr(huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("Output directory").
				Description("Directory under internal/resources/ where the file is written. Example: appplatform").
				Placeholder("appplatform").
				Validate(notEmpty()).
				Value(&resourceDir),

			huh.NewConfirm().
				Title("Skip formatting").
				Description("Disable gofmt after generation. Useful when debugging template output.").
				Value(&skipFormatting),
		),
	).Run())

	// Step 6: Ask for acceptance test options.
	var grafanaVersion string
	var isEnterprise bool

	abortIfErr(huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("Minimum Grafana version").
				Description("Semver constraint for acceptance tests (e.g. >=11.0.0). Leave empty to skip version gating.").
				Placeholder(">=11.0.0").
				Value(&grafanaVersion),

			huh.NewConfirm().
				Title("Enterprise resource?").
				Description("Use CheckEnterpriseTestsEnabled (yes) or CheckOSSTestsEnabled (no) in acceptance tests.").
				Value(&isEnterprise),
		),
	).Run())

	// Step 7: Warn if the resource scaffold already exists.
	name := codegen.SnakeCase(kindInfo.Kind)
	scaffoldFile := filepath.Join(rootOutputDir, "internal", "resources", resourceDir, name+"_resource.go")
	if _, err := os.Stat(scaffoldFile); err == nil {
		fmt.Printf("\nWARNING: %s already exists and will be overwritten.\n\n", scaffoldFile)
		var proceed bool
		abortIfErr(huh.NewForm(
			huh.NewGroup(
				huh.NewConfirm().
					Title("Overwrite existing file?").
					Description("The resource scaffold file already exists. Overwriting it will discard any manual edits.").
					Value(&proceed),
			),
		).Run())

		if !proceed {
			fmt.Println("Aborted.")
			return
		}
	}

	// Step 8: Generate.
	fmt.Println("Generating…")
	manifestProperties := manifest.Properties()
	if err := codegen.Generate(context.Background(), codegen.Config{
		PackageValue:      &kindInfo.Schema,
		KindName:          kindInfo.Kind,
		PluralName:        kindInfo.PluralName,
		Version:           selectedVersion,
		AppName:           manifestProperties.AppName,
		GoTypesImportPath: goTypesImportPath,
		GroupOverride:     manifestProperties.FullGroup,
		ResourceOutputDir: resourceDir,
		SkipFormatting:    skipFormatting,
		GrafanaVersion:    grafanaVersion,
		IsEnterprise:      isEnterprise,
		TemplatesDir:      filepath.Join(cwd, "codegen", "templates"),
		OutputDir:         rootOutputDir,
	}); err != nil {
		panic(fmt.Errorf("generation failed: %w", err))
	}

	fmt.Println("\nGenerated:\n")
	fmt.Printf("  internal/resources/%s/%s_%s_resource.go          — scaffold: review and customize to your needs\n", resourceDir, name, selectedVersion)
	fmt.Printf("  internal/resources/%s/%s_%s_resource_acc_test.go – acceptance test scaffold: implement\n", resourceDir, name, selectedVersion)
	fmt.Println("\nNext steps:\n")
	fmt.Printf("  1. Review and customize internal/resources/%s/%s_%s_resource.go\n", resourceDir, name, selectedVersion)
	fmt.Printf("  2. Register the resource in pkg/provider/resources.go\n")
	fmt.Printf("  3. Declare ownership of the resource in internal/resources/%s/catalog-resource.yaml\n", resourceDir)
	fmt.Printf("  4. Run `go mod tidy && go mod vendor` in the repository root to install the dependencies required for %s\n", kindInfo.PluralName)
	fmt.Printf("  5. Write acceptance tests in internal/resources/%s/%s_%s_resource_acc_test.go\n", resourceDir, name, selectedVersion)
}

func notEmpty() func(s string) error {
	return func(s string) error {
		if strings.TrimSpace(s) == "" {
			return fmt.Errorf("required")
		}
		return nil
	}
}

func abortIfErr(err error) {
	if err == nil {
		return
	}

	if errors.Is(err, huh.ErrUserAborted) {
		os.Exit(0)
	}

	panic(err)
}
