---
kind: pipeline
name: lint
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - golangci-lint --version
  - golangci-lint run ./...
  image: grafana/build-container:1.4.7
  name: lint
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
kind: pipeline
name: docs
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - apk add git
  - go generate
  - if [ -n "$(git status --porcelain)" ]; then
  - '  echo "docs are out of sync, run \"go generate\""'
  - '  exit 1'
  - fi
  image: golang:1.16-alpine
  name: check for drift
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
kind: pipeline
name: oss tests
platform:
  arch: amd64
  os: linux
services:
- environment:
    GF_DATABASE_URL: sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL
  image: grafana/grafana:8.2.5
  name: grafana
steps:
- commands:
  - sleep 5
  - make testacc-oss
  environment:
    GRAFANA_AUTH: admin:admin
    GRAFANA_ORG_ID: 1
    GRAFANA_URL: http://grafana:3000
  image: grafana/build-container:1.4.7
  name: tests
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
kind: pipeline
name: cloud tests
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - make testacc-cloud
  environment:
    GRAFANA_AUTH:
      from_secret: grafana-api-token
    GRAFANA_ORG_ID: 1
    GRAFANA_SM_ACCESS_TOKEN:
      from_secret: grafana-sm-token
    GRAFANA_URL: https://terraformprovidergrafana.grafana.net/
  image: grafana/build-container:1.4.7
  name: tests
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
get:
  name: api-key
  path: infra/data/ci/terraform-provider-grafana/cloud
kind: secret
name: grafana-api-token
---
get:
  name: sm-access-token
  path: infra/data/ci/terraform-provider-grafana/cloud
kind: secret
name: grafana-sm-token
---
kind: signature
hmac: 1a3927e9946f0d8c6de54b49b1b74effa4c33beed747cc0f2ea637d147187aba

...
