---
kind: pipeline
name: lint
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - golangci-lint --version
  - golangci-lint run ./...
  image: golangci/golangci-lint
  name: lint
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
kind: pipeline
name: docs
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - go generate
  - gitstatus="$(git status --porcelain)"
  - if [ -n "$gitstatus" ]; then
  - '  echo "$gitstatus"'
  - '  echo "docs are out of sync, run \"go generate\""'
  - '  exit 1'
  - fi
  image: golang:1.18
  name: check for drift
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
kind: pipeline
name: unit tests
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - go test ./...
  image: golang:1.18
  name: tests
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
concurrency:
  limit: 1
kind: pipeline
name: cloud api tests
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - make testacc-cloud-api
  environment:
    GRAFANA_CLOUD_API_KEY:
      from_secret: grafana-cloud-api-key
    GRAFANA_CLOUD_ORG: terraformprovidergrafana
  image: golang:1.18
  name: tests
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
concurrency:
  limit: 1
kind: pipeline
name: cloud instance tests
platform:
  arch: amd64
  os: linux
services: []
steps:
- commands:
  - make testacc-cloud-instance
  environment:
    GRAFANA_AUTH:
      from_secret: grafana-api-token
    GRAFANA_ORG_ID: 1
    GRAFANA_SM_ACCESS_TOKEN:
      from_secret: grafana-sm-token
    GRAFANA_URL: https://terraformprovidergrafana.grafana.net/
    GRAFANA_AMIXR_ACCESS_TOKEN:
      from_secret: grafana-amixr-token
  image: golang:1.18
  name: tests
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
get:
  name: cloud-api-key
  path: infra/data/ci/terraform-provider-grafana/cloud
kind: secret
name: grafana-cloud-api-key
---
get:
  name: api-key
  path: infra/data/ci/terraform-provider-grafana/cloud
kind: secret
name: grafana-api-token
---
get:
  name: sm-access-token
  path: infra/data/ci/terraform-provider-grafana/cloud
kind: secret
name: grafana-sm-token
---
get:
  name: amixr-access-token
  path: infra/data/ci/terraform-provider-grafana/cloud
kind: secret
name: grafana-amixr-token
---
kind: pipeline
name: 'oss tests: 8.5.0'
platform:
  arch: amd64
  os: linux
services:
- environment:
    GF_DATABASE_URL: sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL
  image: grafana/grafana:8.5.0
  name: grafana
steps:
- commands:
  - sleep 5
  - make testacc-oss
  environment:
    GRAFANA_AUTH: admin:admin
    GRAFANA_ORG_ID: 1
    GRAFANA_URL: http://grafana:3000
    GRAFANA_VERSION: 8.5.0
  image: golang:1.18
  name: tests
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
kind: pipeline
name: 'oss tests: 8.4.7'
platform:
  arch: amd64
  os: linux
services:
- environment:
    GF_DATABASE_URL: sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL
  image: grafana/grafana:8.4.7
  name: grafana
steps:
- commands:
  - sleep 5
  - make testacc-oss
  environment:
    GRAFANA_AUTH: admin:admin
    GRAFANA_ORG_ID: 1
    GRAFANA_URL: http://grafana:3000
    GRAFANA_VERSION: 8.4.7
  image: golang:1.18
  name: tests
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
kind: pipeline
name: 'oss tests: 8.3.7'
platform:
  arch: amd64
  os: linux
services:
- environment:
    GF_DATABASE_URL: sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL
  image: grafana/grafana:8.3.7
  name: grafana
steps:
- commands:
  - sleep 5
  - make testacc-oss
  environment:
    GRAFANA_AUTH: admin:admin
    GRAFANA_ORG_ID: 1
    GRAFANA_URL: http://grafana:3000
    GRAFANA_VERSION: 8.3.7
  image: golang:1.18
  name: tests
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
kind: pipeline
name: 'oss tests: 8.2.7'
platform:
  arch: amd64
  os: linux
services:
- environment:
    GF_DATABASE_URL: sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL
  image: grafana/grafana:8.2.7
  name: grafana
steps:
- commands:
  - sleep 5
  - make testacc-oss
  environment:
    GRAFANA_AUTH: admin:admin
    GRAFANA_ORG_ID: 1
    GRAFANA_URL: http://grafana:3000
    GRAFANA_VERSION: 8.2.7
  image: golang:1.18
  name: tests
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
kind: pipeline
name: 'oss tests: 7.5.15'
platform:
  arch: amd64
  os: linux
services:
- environment:
    GF_DATABASE_URL: sqlite3:///var/lib/grafana/grafana.db?cache=private&mode=rwc&_journal_mode=WAL
  image: grafana/grafana:7.5.15
  name: grafana
steps:
- commands:
  - sleep 5
  - make testacc-oss
  environment:
    GRAFANA_AUTH: admin:admin
    GRAFANA_ORG_ID: 1
    GRAFANA_URL: http://grafana:3000
    GRAFANA_VERSION: 7.5.15
  image: golang:1.18
  name: tests
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
type: docker
workspace:
  path: /drone/terraform-provider-grafana
---
kind: signature
hmac: 6ff6d080f8016b9d41ac6f560d82c5bb0ea1a267e30adbf66fd2e99b1be6b5b0

...
