name: CODEOWNERS check
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  codeowners_check:
    name: CODEOWNERS is in sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
      - name: Check CODEOWNERS is up to date
        run: make codeowners-check
