name: Validate catalog
on:
  pull_request: {}

permissions:
  contents: read

jobs:
  validate-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: ./.github/actions/validate-catalog

