package codegen

import (
	"context"
	"path/filepath"

	"cuelang.org/go/cue"
	"github.com/grafana/codejen"
)

type Config struct {
	// PackageValue is the pre-compiled CUE package value from FetchAndParseManifest.
	PackageValue *cue.Value
	// KindName is the kind name extracted from the CUE file (e.g. "Check").
	KindName string
	// PluralName is the plural name extracted from the CUE file (e.g. "checks").
	PluralName string
	// Version is the selected API version (e.g. "v0alpha1").
	Version string
	// AppName is the Grafana app module name from the manifest (e.g. "correlations").
	AppName string
	// GoTypesImportPath is the import path for the types that were generated by the app-sdk.
	GoTypesImportPath string
	// GroupOverride is extracted from the CUE file (e.g. "advisor.grafana.app").
	GroupOverride string
	// ResourceOutputDir is the target directory under internal/resources (e.g. "appplatform").
	ResourceOutputDir string
	// SkipFormatting disables gofmt/goimports after generation.
	SkipFormatting bool
	// GrafanaVersion is the minimum Grafana version required for acceptance tests (e.g. ">=11.0.0").
	GrafanaVersion string
	// IsEnterprise indicates whether acceptance tests should use CheckEnterpriseTestsEnabled (true)
	// or CheckOSSTestsEnabled (false).
	IsEnterprise bool
	// TemplatesDir specifies the directory in which template files are located.
	TemplatesDir string
	// OutputDir specifies the root directory in which files will be written.
	OutputDir string
}

func Generate(ctx context.Context, config Config) error {
	jennies := codejen.JennyListWithNamer(func(_ cue.Value) string {
		return "CueResourceGenerator"
	})
	resourceOutputDir := filepath.Join("internal", "resources", config.ResourceOutputDir)

	jennies.Append(&GoResourceGenerator{
		kindName:          config.KindName,
		pluralName:        config.PluralName,
		version:           config.Version,
		appName:           config.AppName,
		goTypesImportPath: config.GoTypesImportPath,
		outputDir:         resourceOutputDir,
		skipFormatting:    config.SkipFormatting,
		templatesDir:      config.TemplatesDir,
	})

	jennies.Append(&GoAccTestGenerator{
		kindName:          config.KindName,
		version:           config.Version,
		appName:           config.AppName,
		groupOverride:     config.GroupOverride,
		outputDir:         resourceOutputDir,
		templatesDir:      config.TemplatesDir,
		grafanaVersion:    config.GrafanaVersion,
		isEnterprise:      config.IsEnterprise,
		goTypesImportPath: config.GoTypesImportPath,
	})

	files, err := jennies.GenerateFS(*config.PackageValue)
	if err != nil {
		return err
	}

	return files.Write(ctx, config.OutputDir)
}
