package codegen

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"cuelang.org/go/cue"
	"github.com/grafana/codejen"
	"github.com/grafana/cog"
	appsdkutil "github.com/grafana/grafana-app-sdk/codegen/jennies"
)

var _ codejen.OneToOne[cue.Value] = &GoResourceGenerator{}

type GoResourceGenerator struct {
	kindName       string
	pluralName     string
	outputDir      string
	templatesDir   string
	skipFormatting bool

	// Import path for the types that were generated by the app-sdk
	goTypesImportPath string

	// Name of the app in https://github.com/grafana/grafana/tree/main/apps/{appFolder}/pkg/apis/{appName}
	appName string

	// version of the resource being generated
	// Ex: v0alpha1, v1, ...
	version string
}

func (jenny *GoResourceGenerator) JennyName() string {
	return "GoResourceGenerator"
}

func (jenny *GoResourceGenerator) Generate(v cue.Value) (*codejen.File, error) {
	rootVal := v

	// os.DirFS wraps jenny.templatesDir as a fs.FS.
	// ParseFS(fs, "custom") in initTemplates will walk "custom/" within that FS,
	// which maps to <templatesDir>/custom/ on disk.
	templatesFS := os.DirFS(jenny.templatesDir)

	// Begin: simulate generateFilesAtDepth(depth = 1) from grafana-app-sdk
	it, err := v.Fields()
	if err != nil {
		return nil, err
	}

	for it.Next() {
		v = it.Value()
		if v.Err() != nil {
			return nil, v.Err()
		}
	}
	// End: simulate generateFilesAtDepth(depth = 1) from grafana-app-sdk

	// Figure out the name to use for the root type envelope
	selectors := appsdkutil.TrimPathPrefix(v.Path(), rootVal.Path()).Selectors()
	fieldName := make([]string, 0, len(selectors))
	for _, s := range selectors {
		fieldName = append(fieldName, s.String())
	}

	envelopeName := exportField(strings.Join(fieldName, ""))

	// Naming function stolen from grafana-app-sdk
	maxNamingDepth := len(v.Path().Selectors()) - 1
	nameFunc := func(_ cue.Value, definitionPath cue.Path) string {
		prefix := ""
		if typePrefix := getTypePrefix(v); typePrefix != "" {
			prefix = typePrefix
		}
		i := 0
		for ; i < len(definitionPath.Selectors()) && i < len(v.Path().Selectors()); i++ {
			if maxNamingDepth > 0 && i >= maxNamingDepth {
				break
			}
			if !appsdkutil.SelEq(definitionPath.Selectors()[i], v.Path().Selectors()[i]) {
				break
			}
		}
		if i > 0 {
			definitionPath = cue.MakePath(definitionPath.Selectors()[i:]...)
		}
		name := strings.Trim(definitionPath.String(), "?#")
		if prefix != "" {
			return fmt.Sprintf("%s.%s", prefix, name)
		}
		return name
	}

	// We're finally ready to do some codegen!
	files, err := cog.TypesFromSchema().
		CUEValue(
			filepath.Base(jenny.outputDir),
			v,
			cog.ForceEnvelope(envelopeName),
			cog.NameFunc(nameFunc),
		).
		SchemaTransformations(cog.PrefixObjectsNames(jenny.kindName)).
		Terraform(cog.TerraformConfig{
			SkipPostFormatting:   jenny.skipFormatting,
			SkipGeneratedHeader:  true,
			CustomTemplatesFS:    templatesFS,
			CustomTemplatesFuncs: jenny.buildTemplateFuncs(),
			Validators: cog.TerraformValidators{
				AttributeCountExactly:   "attributeCountExactly",
				RequireAttrsWhenPresent: "requireAttrsWhenPresent",
			},
		}).
		Run(context.Background())
	if err != nil {
		return nil, err
	}

	outputPath := filepath.Join(jenny.outputDir, fmt.Sprintf("%s_%s_resource.go", SnakeCase(jenny.kindName), jenny.version))
	return codejen.NewFile(outputPath, files[0].Data, jenny), nil
}

// buildTemplateFuncs returns the function map injected into cog's template engine.
// These functions give the `object_all_custom_methods` template access to kind metadata
// for auto-generating SpecParser/SpecSaver field mappings.
func (jenny *GoResourceGenerator) buildTemplateFuncs() map[string]any {
	return map[string]any{
		// Metadata accessors used in the template.
		"kindName":       func() string { return jenny.kindName },
		"pluralName":     func() string { return jenny.pluralName },
		"version":        func() string { return jenny.version },
		"kindImportPath": func() string { return jenny.goTypesImportPath },
	}
}
