package codegen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"cuelang.org/go/cue"
	"github.com/grafana/codejen"
)

var _ codejen.OneToOne[cue.Value] = &GoAccTestGenerator{}

type GoAccTestGenerator struct {
	kindName       string
	version        string
	appName        string
	groupOverride  string
	outputDir      string
	templatesDir   string
	grafanaVersion string
	isEnterprise   bool

	// Import path for the types that were generated by the app-sdk
	goTypesImportPath string
}

type accTestTemplateData struct {
	Version        string
	UpperVersion   string
	KindImportPath string
	VarPrefix      string
	TFResourceType string
	LowerName      string
	KindName       string
	CheckFunc      string
	VersionArg     string
}

func (jenny *GoAccTestGenerator) JennyName() string {
	return "GoAccTestGenerator"
}

func (jenny *GoAccTestGenerator) Generate(_ cue.Value) (*codejen.File, error) {
	apiGroup := jenny.appName
	if jenny.groupOverride != "" {
		apiGroup = strings.Split(jenny.groupOverride, ".")[0]
	}

	lowerName := strings.ToLower(jenny.kindName)
	upperVersion := strings.ToUpper(string(jenny.version[0])) + jenny.version[1:]
	varPrefix := strings.ToLower(string(jenny.kindName[0])) + jenny.kindName[1:] + upperVersion
	tfResourceType := fmt.Sprintf("grafana_apps_%s_%s_%s", apiGroup, lowerName, jenny.version)

	checkFunc := "CheckOSSTestsEnabled"
	if jenny.isEnterprise {
		checkFunc = "CheckEnterpriseTestsEnabled"
	}

	versionArg := ""
	if jenny.grafanaVersion != "" {
		versionArg = fmt.Sprintf(", %q", jenny.grafanaVersion)
	}

	tmplPath := filepath.Join(jenny.templatesDir, "acc_test.tmpl")
	tmplContent, err := os.ReadFile(tmplPath)
	if err != nil {
		return nil, fmt.Errorf("reading acc test template: %w", err)
	}

	tmpl, err := template.New("acc_test").Parse(string(tmplContent))
	if err != nil {
		return nil, fmt.Errorf("parsing acc test template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, accTestTemplateData{
		Version:        jenny.version,
		UpperVersion:   upperVersion,
		KindImportPath: jenny.goTypesImportPath,
		VarPrefix:      varPrefix,
		TFResourceType: tfResourceType,
		LowerName:      lowerName,
		KindName:       jenny.kindName,
		CheckFunc:      checkFunc,
		VersionArg:     versionArg,
	}); err != nil {
		return nil, fmt.Errorf("executing acc test template: %w", err)
	}

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		// Return an unformatted source so the user can see what went wrong.
		formatted = []byte(buf.String())
	}

	outputPath := filepath.Join(jenny.outputDir, fmt.Sprintf("%s_%s_resource_acc_test.go", SnakeCase(jenny.kindName), jenny.version))
	return codejen.NewFile(outputPath, formatted, jenny), nil
}
